version: '3.8'
services:
  db:
    container_name: db
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=spring-banking
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3307:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  banking:
    container_name: banking
    build:
      context: .
      dockerfile: ./Dockerfile
    image:
      amartirosyan575/banking.banking
    ports:
      - '5001:8080'
    restart: on-failure
    depends_on:
      - db
volumes:
  db:
    driver: local